### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by srinubalsu** [behzadkh/ArtemisRestExample#1]
Hi,
Tried to follow the instructions and it is not working. It is throwing the following error:

15-Nov-2018 16:06:30.014 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener
 java.lang.RuntimeException: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.]
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:54)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1780)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: ActiveMQNotConnectedException[errorType=NOT_CONNECTED message=AMQ119007: Cannot connect to server(s). Tried with all available servers.]
	at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:790)
	at org.apache.activemq.artemis.rest.MessageServiceManager.start(MessageServiceManager.java:150)
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:50)
	... 13 more

15-Nov-2018 16:06:30.703 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener
 java.lang.NullPointerException
	at org.apache.activemq.artemis.rest.MessageServiceManager.stop(MessageServiceManager.java:209)
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextDestroyed(RestMessagingBootstrapListener.java:61)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1780)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

15-Nov-2018 16:06:32.325 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener
 java.lang.RuntimeException: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"root"). Expected elements are <{}rest-messaging>
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:54)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1780)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"root"). Expected elements are <{}rest-messaging>
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:726)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:247)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:242)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:109)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1131)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:556)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:619)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3129)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at org.apache.activemq.artemis.rest.MessageServiceManager.start(MessageServiceManager.java:128)
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextInitialized(RestMessagingBootstrapListener.java:50)
	... 13 more

15-Nov-2018 16:06:32.329 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener
 java.lang.NullPointerException
	at org.apache.activemq.artemis.rest.MessageServiceManager.stop(MessageServiceManager.java:203)
	at org.apache.activemq.artemis.rest.integration.RestMessagingBootstrapListener.contextDestroyed(RestMessagingBootstrapListener.java:61)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4785)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5404)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:160)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:586)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1780)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by behzadkh** [comment]
tell me how do you use artemis ? i mean by standalone or by embeded in wildfly or something.

**Comment by srinubalsu** [comment]
Hi Behzad,
I am running your github project as standalone in netbeans. On the other
hand, I am running the docker from the
https://hub.docker.com/r/vromero/activemq-artemis/ with below command.

docker run -it --rm -p 8161:8161 -p 5672:5672 -p 61616:61616 -p 55945:55945
-e ENABLE_JMX=true -e JMX_PORT=1199 -e JMX_RMI_PORT=1198  -e
DISABLE_SECURITY=true   vromero/activemq-artemis

Please guide from here. BTW, I am tester, trying to enable rest-proxy on
artemis to test with ReadyAPI Test tool.

Thanks again with your great help, I really appreciate that.

Regards,
Srinu

**Comment by behzadkh** [comment]
Please download and try again because rest dependency version was old

**Comment by srinubalsu** [comment]
Thanks a lot for quick response. I will keep you posted.

Regards,
Srinu

**Comment by srinubalsu** [comment]
Hi Behzad,
I got the attached error while running the latest project.

When I queried for queue data:
[image: image.png]
I see the queue in the artemis console:
[image: image.png]

Please let me know if I am missing anything here.

**Comment by behzadkh** [comment]
please put the error here till i see what happened

**Comment by behzadkh** [comment]
and also put your query

**Comment by behzadkh** [comment]
Hi Srinu,
Do you solve the problem you have mentioned?
Kind regards,
Behzad khosrojerdi


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/30/18,
9:14:42 PM

**Comment by srinubalsu** [comment]
Hi Behzad,
Thanks for coming back. You are really awesome. Due to time constraints, I
stopped going through the rest solution and started using Jolokia for my
rest calls. Even though I don’t like that approach, I am trying to make it
work.

Btw, has it worked for you locally? As I mentioned to you it was throwing
those error as I mentioned in the log file before.

Thanks for your patience,

Regards,
Srinu

**Comment by behzadkh** [comment]
Hi Srinu,
I just want to tell you that i use apache artmis verion 2.1 and it was not
good to call rest
 because i could call some of them and some others did not work
and i recommend use jolokia as you said and certainly take advantage of
admin (managemnt application that recently you can use to monitor your
queues or topics because there are operation that show you the comment
which you can call it from your app.
I mean it gives you rest query string like samples that shows you how to
call rest from jolokia
kind regards,
behzad khosrojerdi


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
12/01/18,
6:32:10 PM

**Comment by srinubalsu** [comment]
Thanks for the response. Have a wonderful day.
